### ISSUE TITLE
Not building on Debian Stable (Trixie) - arm64 architecture

### ISSUE THREAD

**Issue by pcardona34** [trunkmaster/nextspace#525]
Hello Sergii,

I have more time now to go back on trying and testing NEXTSPACE evolving.

So I began from a fresh Debian Stable Lite (Trixie 13.3) on my new arm64 architecture (pi 500).
My thought was to duplicate debian-12  deps to debian-13 and check dependencies step by step.

- I first installed `binutils-gold` and `clang` to fix first missing messages.
- Then I tried to build again `libdispatch` (stage 0) but I was early stuck at 13%:

> Apply.c:366:4: error:cast from 'dispatch_function_t' (aka 'void(*)void* _Nullable') to dispatch_apply_function_t' (aka  'void (*) void *, unsigned ling)') converts to incompatible function type [-Werror, -Wcast-function-type-mismatch]
> 366 |  (dispatch_apply_function_t)_dispatch_Block_invoke(work));
> |
> 1 error generated
>  (...)

**Comment by felixding** [comment]
I went through the same process twice recently. Instead of manually fixing the build scripts, I just asked Claude Code/OpenAI Codex to run all the steps for me and fix any issue it encounters. Then I manually ran the user creation scripts.

Unfortunately, then I got stuck at https://github.com/trunkmaster/nextspace/issues/524

**Comment by kuau** [comment]
Is it now possible to build from the master source on Debian 13.5 amd64?

**Comment by armm77** [comment]
Hi @kuau,not yet, it still needs some adjustments. Try this change: https://github.com/trunkmaster/nextspace/pull/538 and let me know. It's been validated with Debian 13.6.

**Comment by kuau** [comment]
Thanks for your help so I should have read your reply a little closer you specifically said Debian 13.6 well stupid me I did the install on 13.5 and it was a challenge though thanks to Grok and some modifications I got it installed I will do another build using 13.6 and see if it goes smoother

**Comment by kuau** [comment]
quick update this fixed everything git clone -b scripts https://github.com/armm77/nextspace.git
this branch worked right out of the gate in Debian 15.6   zero errors during the build process.

**Comment by MagnetarRocket** [comment]
`Debian 15.6`??

Did you just mistype or are you actually on a testing build of debian @kuau?

**Comment by kuau** [comment]
Oops I meant 13.6 Debian sorry about that

**Comment by pcardona34** [comment]
That is great to know. As I also replaced my particular screen by a new one obviously more standard, it will be worth to try it again from armm77's  fork. I'll let you know.

**Comment by kuau** [comment]
Now if I can only figure out any kind of power management / screen saver setup with my completed build that actually works would be great

**Comment by pcardona34** [comment]
@armm77 
All is working as expected with your fork and the `-b scripts` option while cloning.  Thank you for the work  done. I tested with a  qemu/kvm arm64 vm.  I confirm the issue is fixed doing so. I do not close the topic because this could be useful for other people.
> [!NOTE]
Also I noted that within debian 13.6 freshly installed from a  netinst iso, `sudo` must be installed first and the current user added to the `sudo` group before you proceed with the nexstspace installation from sources.

**Comment by pcardona34** [comment]
@kuau 
Did you try to install InnerSpace.app to manage screen saver?

**Comment by kuau** [comment]
Yes I did yet I figured out what was going on with my system so it turns out a bug in my Asus monitor and the display port so all I had to do was in the OSD change it from auto detect to just display port and know with no screensaver my display goes to sleep by itself and wakes up. I am currently testing the same build yet using the FreeBSD branch and that seems to be working well to except the Login.app which is documented still not functioning
